### ISSUE TITLE
 get_utm_srid_from_lonlat function

### ISSUE THREAD

**Issue by fitraelbi** [enricofer/wide_sight#5]
`    
  class panoramas_serializer(serializers.ModelSerializer):
      
      def get_utm_geom(self,obj):
          if obj.lon and obj.lat:
              
              utm_srid = get_utm_srid_from_lonlat(obj.lon,obj.lat)
             
`

i don't understand where function get_utm_srid_from_lonlat came from, could you explain me where this function resource  ?  on the wide_sight serializers.py

**Comment by enricofer** [comment]
This is a not operating portion of code, apparently lost here during development  (the not imported function would throw an exception if encounterd during the flow of execution). The function is used in models.py to fill utm_srid: https://github.com/enricofer/wide_sight/blob/ca445674f84458c05b90c852ecf7c94447042da6/wide_sight/models.py#L24 https://github.com/enricofer/wide_sight/blob/ca445674f84458c05b90c852ecf7c94447042da6/wide_sight/models.py#L117
